FROM nginx

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/fuadapuq/CC.git /tmp/repo
RUN ls -lah /tmp/repo
RUN cp -r /tmp/repo/* /usr/share/nginx/html/

EXPOSE 80
